### ISSUE TITLE
needs dependencies optimisation

### ISSUE THREAD

**Issue by okliv** [blazeeboy/rubrowser#1]
Parsing documentation for rack-protection-1.5.3
Installing ri documentation for rack-protection-1.5.3
Parsing documentation for sinatra-1.4.7
Installing ri documentation for sinatra-1.4.7

Done installing documentation for rack-protection, sinatra, ast, parser, parallel, haml, rubrowser after 273 seconds
7 gems installed

after 273 seconds! =)

is this necessary?

**Comment by blazeeboy** [comment]
oh, that is a long time to parse docs I guess, maybe installing without `ri` will help cut down time.
another point, I guess `rack-protection` is a requirement for `sinatra`, I'll look into it and see if I can remove it from dependencies somehow.

thanks for the heads up.

**Comment by blazeeboy** [comment]
well `rack-protection` gem is merged to sinatra master so I guess it won't be installed separately in the next release, so If we decided to cut down installation time we'll have to remove sinatra and run our own http server.
and also looks like the main problem is documentation parsing, If you don't need it you can install it via : 
```
gem install --no-ri --no-rdoc
```

**Comment by blazeeboy** [comment]
removed all dependencies but `parser` gem as we can't redo what it does in a simple way (i guess 😄 )
