### ISSUE TITLE
yard graph vs rubrowser

### ISSUE THREAD

**Issue by arbox** [blazeeboy/rubrowser#2]
Hi!
Thanks for the nice project!
Look at `yard graph` for additional inspiration, it's a pretty standard tool for class diagram and dependency visualizations for Ruby projects.

**Comment by blazeeboy** [comment]
I tried it now, the diagram looks interesting, I would like to take the additional parsing information from Yard like attributes/methods for the "details" panel in rubrowser
YARD would be a complete backend and rubrowser is a frontend if it was parsing the classes dependencies not just the inheritance/composition, as from what I see now, if a class is using another class or module it doesn't display it (unless it's included or extended).
am I missing some command flag?
I used this command to generate the graph for one of [my projects](https://github.com/blazeeboy/amun)
```
yard doc
yard graph --dependencies --empty-mixins --full | dot -T pdf -o diagram.pdf
```
and the resulting graph was as such 
[diagram.pdf](https://github.com/blazeeboy/rubrowser/files/914490/diagram.pdf)

**Comment by arbox** [comment]
You are right, Yard wouldn't say you if a class instance is created or called somewhere else in the code. But you cannot collect such information statically in an easy way since objects can by passed dynamically as arguments, types can be casted and so on...

Three ways so are possible:
- sophisticated static analysis;
- dynamic runtime analysis;
- type annotations.

It's definitely not so easy as for the first glance :) But please keep trying!
